/**
 * The exact faces loaded at startup. Keys are the strings used as `fontFamily`
 * in `typography.ts` — the two files must stay in step.
 *
 * These are Latin subsets generated by `scripts/subset-fonts.sh`, not the npm
 * packages: M PLUS Rounded 1c carries CJK coverage, so the full faces are
 * ~3.3MB *each* — three weights would ship ~10MB of font binary to set English
 * text. The subsets are ~65KB per weight. The @expo-google-fonts packages stay
 * in devDependencies as the source the script subsets from; re-run it after
 * bumping them.
 *
 * Kept separate from `typography.ts` so unit tests can import the type scale
 * without dragging font binaries through the module graph.
 */
export const fontAssets = {
  MPLUSRounded1c_400Regular: require('../../assets/fonts/MPLUSRounded1c_400Regular.ttf'),
  MPLUSRounded1c_500Medium: require('../../assets/fonts/MPLUSRounded1c_500Medium.ttf'),
  MPLUSRounded1c_700Bold: require('../../assets/fonts/MPLUSRounded1c_700Bold.ttf'),
  ShantellSans_400Regular: require('../../assets/fonts/ShantellSans_400Regular.ttf'),
};
