#!/usr/bin/env node
/**
 * Write traced path data into the app as a generated TypeScript module.
 *
 * Usage:  node scripts/art-to-code.mjs
 *
 * Path data is generated, bulky and meaningless to read; the components that
 * draw it are hand-written and worth reading. Keeping them in separate files is
 * what lets a re-trace be a one-command overwrite that never touches a
 * component, and keeps a 10KB blob out of the file you actually edit.
 *
 * Marks are collected by *name* across every traced sheet, not per sheet. Which
 * page a drawing happened to be printed on is a fact about paper: sheets are
 * repaginated whenever the box size changes, and a mark that moved between them
 * must not need a code change to follow. The manifest says which names are
 * icons; everything here reads from that.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TRACED = resolve(ROOT, 'art/traced');
const camel = (k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

const manifest = JSON.parse(
  readFileSync(resolve(ROOT, 'art/templates/justsit.manifest.json'), 'utf8'));
const wanted = manifest.sheets
  .flatMap((s) => s.cells)
  .filter((c) => c.kind === 'icon')
  .map((c) => c.key);

/** Every traced mark on disk, and which file each came from. */
const traced = {};
const from = {};
if (existsSync(TRACED)) {
  for (const f of readdirSync(TRACED).filter((f) => f.endsWith('.json') && !f.endsWith('.report.json')).sort()) {
    for (const [k, v] of Object.entries(JSON.parse(readFileSync(resolve(TRACED, f), 'utf8')))) {
      traced[k] = v;
      from[k] = f;
    }
  }
}

const have = wanted.filter((k) => traced[k]?.length);
const missing = wanted.filter((k) => !traced[k]?.length);
if (!have.length) {
  console.error('No traced icons found in art/traced — trace a sheet first.');
  process.exit(1);
}
if (missing.length) {
  console.error(`Missing traced icons: ${missing.join(', ')}. ` +
    'Generating without them would break the components that draw them.');
  process.exit(1);
}

// An empty box contributes nothing rather than an empty mark, so a partial
// re-draw leaves the rest standing from whatever sheet traced them last. That is
// the right behaviour and a silent one: sheets drawn at different box sizes carry
// different stroke weights, and nothing downstream can tell.
const sources = [...new Set(have.map((k) => from[k]))];
if (sources.length > 1) {
  console.warn(`  note: icons come from ${sources.length} sheets — ${
    have.map((k) => `${k} <- ${from[k]}`).join(', ')}\n` +
    '  Weights only agree if those sheets used the same box size.');
}

const body = have
  .map((key) => `  ${camel(key)}: [\n${traced[key].map((d) => `    '${d}',`).join('\n')}\n  ],`)
  .join('\n');

const out = `/**
 * Generated by scripts/art-to-code.mjs from art/traced/*.json. Do not edit.
 *
 * Outlines of marks drawn by hand and traced, on the 48-unit canvas the doodles
 * share. These are filled shapes rather than stroked centrelines: the nib lives
 * in the outline, so the pressure and the way a stroke ends survive instead of
 * being thrown away and re-stroked at a uniform width.
 */
export const ICON_PATHS = {
${body}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

const dest = resolve(ROOT, 'src/ui/icons.paths.ts');
writeFileSync(dest, out);
console.log(`${dest}  ${have.length} icons, ${(out.length / 1024).toFixed(1)} KB`);
